# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-17 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborupdate', '0002_auto_20180317_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='neigh_location',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='neigh_name',
        ),
    ]
