# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-17 12:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neighborupdate', '0003_auto_20180317_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neigh_name', models.CharField(max_length=30, null=True)),
                ('neigh_location', models.CharField(max_length=30, null=True)),
                ('occupants_count', models.IntegerField(default=0)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
