# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-17 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighborupdate', '0004_neighbourhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='neighbourhood_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neighborupdate.Neighbourhood'),
        ),
    ]
