# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-19 06:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neighborupdate', '0005_profile_neighbourhood_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=30, null=True)),
                ('business_email', models.EmailField(max_length=254, null=True)),
                ('business_description', models.TextField(null=True)),
                ('neighborhood_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neighborupdate.Neighbourhood')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('post', models.TextField(null=True)),
                ('post_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('neighborhood_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neighborupdate.Neighbourhood')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-post_date'],
            },
        ),
    ]
